import customScalarsExchange from 'urql-custom-scalars-exchange';
import { GraphQLDateTime, GraphQLDate } from 'graphql-scalars';

import schema from '../schema.json';

export default customScalarsExchange({
  // @ts-ignore: The Schema type is autogenerated but doesn't match *exactly*
  schema,
  scalars: {
    ISO8601DateTime: (value) => GraphQLDateTime.parseValue(value),
    ISO8601Date: (value) => GraphQLDate.parseValue(value),
  },
});
