export default [
  { id: 'en-us', text: 'English (American)' },
  // { id: 'en-au', text: 'English (Australian)' },
  // { id: 'en-ca', text: 'English (Canadian)' },
  { id: 'en-gb', text: 'English (British)' },
  // { id: 'af-za', text: 'Afrikaans' },
  // { id: 'ar-001', text: 'العربية' }, // rtl
  // { id: 'bn-bd', text: 'বাংলা (বাংলাদেশ)' },
  // { id: 'bg-bg', text: 'Български' },
  { id: 'ca-es', text: 'Català' },
  // { id: 'zh-cn', text: '中文 (简体)' },
  // { id: 'zh-tw', text: '中文 (繁體)' },
  // { id: 'hr-hr', text: 'Hrvatski' },
  // { id: 'cs-cz', text: 'Česky' },
  // { id: 'da-dk', text: 'Dansk' },
  // { id: 'nl-nl', text: 'Nederlands' },
  // { id: 'et-ee', text: 'Eesti Keel' },
  // { id: 'fi-fi', text: 'Suomi' },
  { id: 'fr-fr', text: 'Français' },
  // { id: 'fr-ca', text: 'Français (Canadien)' },
  { id: 'de-de', text: 'Deutsch' },
  // { id: 'el-gr', text: 'Ελληνικά' },
  // { id: 'he-il', text: 'עברית' }, // rtl
  // { id: 'hi-in', text: 'हिन्दी' },
  { id: 'hu-hu', text: 'Magyar' },
  // { id: 'is-is', text: 'Íslenska' },
  { id: 'id-id', text: 'Bahasa Indonesia' },
  // { id: 'ga-ie', text: 'Gaeilge' },
  { id: 'it-it', text: 'Italiano' },
  // { id: 'ja-jp', text: '日本語' },
  // { id: 'kk-kz', text: 'Қазақ' },
  // { id: 'ko-kr', text: '한국어' },
  // { id: 'lv-lv', text: 'Latviešu' },
  // { id: 'lt-lt', text: 'Lietuvių Kalba' },
  // { id: 'ms-my', text: 'Bahasa Melayu' },
  // { id: 'mt-mt', text: 'Malti' },
  // { id: 'nb-no', text: 'Norsk (Bokmål)' },
  // { id: 'nn-no', text: 'Norsk (Nynorsk)' },
  // { id: 'fa-ir', text: 'فارسی' }, // rtl
  // { id: 'pl-pl', text: 'Polski' },
  { id: 'pt-pt', text: 'Português' },
  { id: 'pt-br', text: 'Português (Brasileiro)' },
  // { id: 'ro-ro', text: 'Română' },
  { id: 'ru-ru', text: 'Русский' },
  // { id: 'sc-it', text: 'Sardu' },
  // { id: 'sco-gb', text: 'Scots' },
  // { id: 'sr-cs', text: 'Srpski' },
  // { id: 'sr-sp', text: 'Српски' },
  // { id: 'sk-sk', text: 'Slovenčina' },
  // { id: 'sl-sl', text: 'Slovenščina' },
  { id: 'es-es', text: 'Español' },
  // { id: 'sv-se', text: 'Svenska' },
  // { id: 'tl-ph', text: 'Wikang Tagalog' },
  // { id: 'th-th', text: 'ไทย' },
  // { id: 'tr-tr', text: 'Türkçe' },
  // { id: 'uk-ua', text: 'Українська' },
  // { id: 'ur-in', text: 'اردو (پاکستانی)' },
  // { id: 'ur-pk', text: 'اردو (ہندوستانی)' },
  // { id: 'vi-vn', text: 'Việtnam' },
  // { id: 'cy-gb', text: 'Cymraeg' }
];
