# import imageFields from 'app/components/Image/imageFields';

query FindMediaByIdAndType($id: ID!, $mediaType: MediaTypeEnum!) {
  findMediaByIdAndType(id: $id, mediaType: $mediaType) {
    ...MediaData
  }
}

fragment MediaData on Media {
  __typename
  id
  slug
  type
  sfw
  titles {
    preferred
  }
  bannerImage {
    ...imageFields
  }
  posterImage {
    ...imageFields
  }
  myLibraryEntry {
    __typename
    id
    nextUnit {
      __typename
      id
      number
    }
    lastUnit {
      __typename
      id
      number
    }
    progress
  }
}
