query FindLibraryEntryById($id: ID!) {
  findLibraryEntryById(id: $id) {
    id
    nextUnit {
      titles {
        preferred
      }
    }
    progress
    media {
      id
      type
      slug
      titles {
        preferred
      }
    }
  }
}
