mutation likeReaction($id: ID!) {
  mediaReaction {
    like(input: { mediaReactionId: $id }) {
      result {
        id
        hasLiked
        likes(first: 1) {
          totalCount
        }
      }
    }
  }
}
