# import animeBannerFields from '../../Anime/Banner/fields';
# import libraryBoxFields from '../LibraryBox/fields';

fragment animeLayoutFields on Anime {
  ...animeBannerFields
  ...libraryBoxFields
}
