# import imageFields from 'app/components/Image/imageFields';

fragment MediaFields on Media {
  id
  type
  slug
  description
  titles {
    preferred
  }
  posterImage {
    ...imageFields
  }
  bannerImage {
    ...imageFields
  }
  myLibraryEntry {
    id
    progress
  }
}
