# import imageFields from 'app/fragments/imageFields';

query loadProfileMenu {
  currentAccount {
    id
    profile {
      id
      slug
      name
      avatarImage {
        ...imageFields
      }
      bannerImage {
        ...imageFields
      }
    }
  }
}
